package CoreGameServerIDL;

/**
* CoreGameServerIDL/GameServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/warrenwhite/eclipse-workspace/COMP-6231-A2/src/GameServer.idl
* Wednesday, June 17, 2020 11:52:35 PM EDT
*/

public final class GameServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CoreGameServerIDL.GameServer value = null;

  public GameServerHolder ()
  {
  }

  public GameServerHolder (CoreGameServerIDL.GameServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CoreGameServerIDL.GameServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CoreGameServerIDL.GameServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CoreGameServerIDL.GameServerHelper.type ();
  }

}
